version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=bd
      - DB_USER=root
      - DB_PASSWORD=qwerty123
      - DB_NAME=first
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 10.10.0.2
    volumes:
      - ./html:/var/www/html
      - db_data:/var/lib/mysql

  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=first
      - MYSQL_USER=meow
      - MYSQL_PASSWORD=342
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 10.10.0.3

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
